chess: ChessMain.cpp ChessBoard.cpp ChessPiece.cpp King.cpp Pawn.cpp Rook.cpp Bishop.cpp Queen.cpp Knight.cpp
	g++ -Wall -g ChessMain.cpp ChessBoard.cpp ChessPiece.cpp King.cpp Pawn.cpp Rook.cpp Bishop.cpp Queen.cpp Knight.cpp -o chess
